version: "3.8"

volumes:
  bundle:

services:
  package:
    image: ruby:3.0
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - BUNDLE_PATH=/vendor/bundle
    volumes:
      - ./:/home/package
      - bundle:/vendor/bundle
