name: ruby gem
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-6-0
          - gemfiles/Gemfile-rails-5-2
          - gemfiles/Gemfile-rails-5-1
          - gemfiles/Gemfile-rails-5-0
        ruby:
          - 2.6
          - 2.7
          - 3.0
        exclude:
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-0
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-1
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-2
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec
