name: ruby gem
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-6-0
          - gemfiles/Gemfile-rails-5-2
          - gemfiles/Gemfile-rails-5-1
          - gemfiles/Gemfile-rails-5-0
        ruby:
          - 2.6
          - 2.7
          - 3.0
        exclude:
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-0
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-1
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-rails-5-2
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5 # Locking to specific version b/c: https://github.com/paambaati/codeclimate-action/issues/142
        if: matrix.ruby == '3.0' && matrix.gemfile == 'Gemfile'
